# Introduction to NumPy
Getting started with Numpy

In [69]:
import numpy as np
np.__version__

'1.15.2'

## Differences between lists and NumPy Arrays
* An array's size is immutable. You cannot append, insert or remove elements, like you can with a list.
* All of an array's elements must be of the same [data type](https://en.wikipedia.org/wiki/Data_type).
* A NumPy array behaves in a Pythonic fashion. You can `len(my_array)` just like you would assume.

In [70]:
mix_list = [5.6, 9.599, 7.95]

In [71]:
#can have element appended to it
mix_list.append(1.23)
#can have multiple datatype in it
mix_list.insert(1, "Whatever")
#can have item removed
mix_list.pop(1)

'Whatever'

In [72]:
mix_list

[5.6, 9.599, 7.95, 1.23]

In [73]:
arr_list = np.array(mix_list)

In [74]:
?arr_list

In [75]:
arr_list.dtype

dtype('float64')

In [76]:
arr_list.itemsize

8

In [77]:
arr_list.size

4

In [78]:
len(arr_list)

4

In [79]:
arr_list.nbytes

32

In [80]:
study_minutes = np.zeros(100)
study_minutes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Saving Space with Data Types

In [81]:
%whos

Variable                Type           Data/Info
------------------------------------------------
arr_list                ndarray        4: 4 elems, type `float64`, 32 bytes
fake_log                ndarray        100: 100 elems, type `uint16`, 200 bytes
first_day_minutes       uint16         180
index                   ndarray        2x2: 4 elems, type `int64`, 32 bytes
mix_list                list           n=4
multydim_arr            ndarray        3x3: 9 elems, type `float16`, 18 bytes
np                      module         <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
rand                    RandomState    <mtrand.RandomState object at 0x107eb7dc8>
study_minutes           ndarray        100: 100 elems, type `float64`, 800 bytes
study_minutes_lighter   ndarray        100: 100 elems, type `uint16`, 200 bytes


We are using 800 bytes to store the **study_minutes** array.  
Because we have to store a number that can't be bigger then the number of the minutes in a day...  
so we don't need the type *float64*, instead we can use the type *unint16* to have a lighter array.

In [82]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [83]:
%whos

Variable                Type           Data/Info
------------------------------------------------
arr_list                ndarray        4: 4 elems, type `float64`, 32 bytes
fake_log                ndarray        100: 100 elems, type `uint16`, 200 bytes
first_day_minutes       uint16         180
index                   ndarray        2x2: 4 elems, type `int64`, 32 bytes
mix_list                list           n=4
multydim_arr            ndarray        3x3: 9 elems, type `float16`, 18 bytes
np                      module         <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
rand                    RandomState    <mtrand.RandomState object at 0x107eb7dc8>
study_minutes           ndarray        100: 100 elems, type `uint16`, 200 bytes
study_minutes_lighter   ndarray        100: 100 elems, type `uint16`, 200 bytes


In [84]:
study_minutes[0] = 180

In [85]:
first_day_minutes = study_minutes[0]

In [86]:
first_day_minutes

180

In [87]:
type(first_day_minutes)

numpy.uint16

In [88]:
study_minutes[1:4] = [200, 120, 300]
study_minutes

array([180, 200, 120, 300,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

## Multidimensional array

* The data structure is actually called `ndarray`, representing any **n**umber of **d**imensions
* Arrays can have multiple dimensions, you declare them on creation
* Dimensions help define what each element in the array represents.  A two dimensional array is just an array of arrays
* **Rank** defines how many dimensions an array contains 
* **Shape** defines the length of each of the array's dimensions
* Each dimension is also referred to as an **axis**, and they are zero-indexed. Multiples are called **axes**.
* A 2d array is AKA **matrix**.

In [89]:
multydim_arr = np.array([
    [5.6, 3.599, 5.75],
    [4.3, 6, 6.95],
    [5.2, 7.599, 7]
], np.float16)
multydim_arr

array([[5.6  , 3.6  , 5.75 ],
       [4.3  , 6.   , 6.95 ],
       [5.2  , 7.598, 7.   ]], dtype=float16)

In [90]:
multydim_arr.ndim

2

In [91]:
multydim_arr.shape

(3, 3)

In [92]:
multydim_arr.size

9

In [93]:
len(multydim_arr)

3

In [94]:
multydim_arr.itemsize

2

In [95]:
multydim_arr.itemsize * multydim_arr.size

18

%whos ndarray

In [96]:
np.info(multydim_arr)

class:  ndarray
shape:  (3, 3)
strides:  (6, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7f979011f200
byteorder:  little
byteswap:  False
type: float16


In [97]:
multydim_arr[2]

array([5.2  , 7.598, 7.   ], dtype=float16)

In [98]:
multydim_arr[2][0]

5.2

## Back to owr challange


In [99]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])

In [100]:
study_minutes.shape

(2, 100)

In [101]:
# Set round 2 day 1 to 60
study_minutes[1][0] = 60
study_minutes

array([[180, 200, 120, 300,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [102]:
study_minutes[1,0] #this is just a touple [(1,0)]

60

## Fancy indexing

### Creation 
* You can create a random but bound grouping of values using the `np.random` package.  
  * `RandomState` let's you seed your randomness in a way that is repeatable.
* You can append a row in a couple of ways
   * You can use the `np.append` method.  Make sure the new row is the same shape.
   * You can create/reassign a new array by including the existing array as part of the iterable in creation.


### Indexing
* You can use an indexing shortcut by separating dimensions with a comma.  
* You can index using a `list` or `np.array`.  Values will be pulled out at that specific index.  This is known as fancy indexing.
  * Resulting array shape matches the index array layout.  Be careful to distinguish between the tuple shortcut and fancy indexing.



In [103]:
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [104]:
[fake_log[3], fake_log[8]]

[44, 50]

In [105]:
fake_log[[3, 8]]

array([44, 50], dtype=uint16)

In [106]:
index = np.array([
    [3, 8],
    [0, 1]
])
fake_log[index]

array([[ 44,  50],
       [132, 122]], dtype=uint16)

In [107]:
study_minutes = np.append(study_minutes, [fake_log], axis=0)

In [108]:
study_minutes

array([[180, 200, 120, 300,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [109]:
study_minutes[1,1] = 360

In [110]:
study_minutes

array([[180, 200, 120, 300,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 60, 360,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [111]:
study_minutes < 60

array([[False, False, False, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  Tru

In [112]:
study_minutes[study_minutes < 60]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31,
       59, 50, 47, 43, 38, 52, 31, 57, 37, 58], dtype=uint16)

In [117]:
results = []
for rounds in study_minutes:
    for value in rounds:
        if value < 60:
            results.append(value)
np.array(results)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31,
       59, 50, 47, 43, 38, 52, 31, 57, 37, 58], dtype=uint16)

In [118]:
np.array([False, True, True]) & np.array([True, False, True])

array([False, False,  True])

In [119]:
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [120]:
study_minutes[study_minutes < 60] = 0

In [121]:
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([], dtype=uint16)