# Introduction to NumPy
Getting started with Numpy

In [23]:
import numpy as np
np.__version__

'1.15.2'

## Differences between lists and NumPy Arrays
* An array's size is immutable. You cannot append, insert or remove elements, like you can with a list.
* All of an array's elements must be of the same [data type](https://en.wikipedia.org/wiki/Data_type).
* A NumPy array behaves in a Pythonic fashion. You can `len(my_array)` just like you would assume.

In [24]:
mix_list = [5.6, 9.599, 7.95]

In [25]:
#can have element appended to it
mix_list.append(1.23)
#can have multiple datatype in it
mix_list.insert(1, "Whatever")
#can have item removed
mix_list.pop(1)

'Whatever'

In [26]:
mix_list

[5.6, 9.599, 7.95, 1.23]

In [27]:
arr_list = np.array(mix_list)

In [28]:
?arr_list

In [29]:
arr_list.dtype

dtype('float64')

In [30]:
arr_list.itemsize

8

In [31]:
arr_list.size

4

In [32]:
len(arr_list)

4

In [33]:
arr_list.nbytes

32

In [34]:
study_minutes = np.zeros(100)
study_minutes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Saving Space with Data Types

In [35]:
%whos

Variable                Type       Data/Info
--------------------------------------------
arr_list                ndarray    4: 4 elems, type `float64`, 32 bytes
first_day_minutes       uint16     300
mix_list                list       n=4
np                      module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
study_minutes           ndarray    100: 100 elems, type `float64`, 800 bytes
study_minutes_lighter   ndarray    100: 100 elems, type `uint16`, 200 bytes


We are using 800 bytes to store the study_minutes array.  
Because we have to store a number that can't be bigger then the number of the minutes in a day...  
so we don't need the type *float64*, instead we can use the type *unint16* to have a lighter array.

In [36]:
study_minutes_lighter = np.zeros(100, np.uint16)
study_minutes_lighter

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [37]:
%whos

Variable                Type       Data/Info
--------------------------------------------
arr_list                ndarray    4: 4 elems, type `float64`, 32 bytes
first_day_minutes       uint16     300
mix_list                list       n=4
np                      module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
study_minutes           ndarray    100: 100 elems, type `float64`, 800 bytes
study_minutes_lighter   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [38]:
study_minutes_lighter[0] = 180

In [39]:
first_day_minutes = study_minutes_lighter[0]

In [40]:
first_day_minutes

180

In [41]:
type(first_day_minutes)

numpy.uint16

In [43]:
study_minutes_lighter[1:4] = [200, 120, 300]
study_minutes_lighter

array([180, 200, 120, 300,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

## Multidimensional array

In [45]:
multydim_arr = np.array([
    [5.6, 3.599, 5.75],
    [4.3, 6, 6.95],
    [5.2, 7.599, 7]
], np.float16)
multydim_arr

array([[5.6  , 3.6  , 5.75 ],
       [4.3  , 6.   , 6.95 ],
       [5.2  , 7.598, 7.   ]], dtype=float16)

In [46]:
multydim_arr.ndim

2

In [47]:
multydim_arr.shape

(3, 3)

In [48]:
multydim_arr.size

9

In [49]:
len(multydim_arr)

3

In [50]:
multydim_arr.itemsize

2

In [51]:
multydim_arr.itemsize * multydim_arr.size

18

In [52]:
%whos ndarray

Variable                Type       Data/Info
--------------------------------------------
arr_list                ndarray    4: 4 elems, type `float64`, 32 bytes
multydim_arr            ndarray    3x3: 9 elems, type `float16`, 18 bytes
study_minutes           ndarray    100: 100 elems, type `float64`, 800 bytes
study_minutes_lighter   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [53]:
np.info(multydim_arr)

class:  ndarray
shape:  (3, 3)
strides:  (6, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7f978dde4000
byteorder:  little
byteswap:  False
type: float16
